apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: test-btp-account
spec:
  timeouts: 
    apply: 10s
    assert: 20s
    cleanup: 120s
  steps:
  - timeouts:
      assert: 600s
    try:
    - apply:
        file: crs/subaccount.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Subaccount
          metadata:
            name: upgrade-test-subaccount
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 120s
    try:
    - apply:
        file: crs/cis-entitlement.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Entitlement
          metadata:
            name: cis-entitlement
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 120s
    try:
    - apply:
        file: crs/kyma-entitlement.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Entitlement
          metadata:
            name: kyma-entitlement
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 480s
    try:
    - apply:
        file: crs/service-manager.yaml
    # Add debugging step before assertion
    - script:
        content: |
          #!/bin/bash
          echo "=== Pre-assertion ServiceManager debug ==="
          kubectl describe servicemanager upgrade-test-subaccount-service-manager
          echo "=== End pre-assertion debug ==="
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1beta1 
          kind: ServiceManager
          metadata:
            name: upgrade-test-subaccount-service-manager
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
    # Add post-assertion validation
    - script:
        content: |
          #!/bin/bash
          echo "=== Post-assertion ServiceManager validation ==="
          kubectl describe servicemanager upgrade-test-subaccount-service-manager
          echo "=== End post-assertion validation ==="
  - timeouts:
      assert: 480s
    try:
    - apply:
        file: crs/cis-local.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1  
          kind: CloudManagement
          metadata:
            name: my-cis
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s  
    try:
    - apply:
        file: crs/cloudfoundry-env.yaml
    - assert:
        resource:
          apiVersion: environment.btp.sap.crossplane.io/v1alpha1 
          kind: CloudFoundryEnvironment
          metadata:
            name: cf-env-dummy-test-upgrade
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s  
    try:
    - apply:
        file: crs/subscription.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Subscription
          metadata:
            name: my-subscription
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 1800s  
    try:
    - apply:
        file: crs/kyma-env.yaml
    - assert:
        resource:
          apiVersion: environment.btp.sap.crossplane.io/v1alpha1 
          kind: KymaEnvironment
          metadata:
            name: my-kyma-env
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'

