apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: sa-provider-secret
type: Opaque
stringData:
    credentials: |
        INJECT_ENV.BTP_TECHNICAL_USER
---
apiVersion: btp.sap.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
    name: account-provider-config
spec:
    globalAccount: "INJECT_ENV.GLOBAL_ACCOUNT"
    cliServerUrl: "INJECT_ENV.CLI_SERVER_URL"
    cisCredentials:
        secretRef:
            name: cis-provider-secret
            namespace: default
            key: data
        source: Secret
    serviceAccountSecret:
        secretRef:
            key: credentials
            name: sa-provider-secret
            namespace: default
        source: Secret
---
apiVersion: v1
kind: Secret
metadata:
    namespace: default
    name: cis-provider-secret
type: Opaque
stringData:
    data: | 
        INJECT_ENV.CIS_CENTRAL_BINDING
