apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: test-btp-account
spec:
  timeouts: 
    apply: 10s
    assert: 20s
    cleanup: 120s
  steps:
  - timeouts:
      assert: 300s
    try:
    - apply:
        file: crs/01_subaccount.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Subaccount
          metadata:
            name: upgrade-test-subaccount
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 120s
    try:
    - apply:
        file: crs/02_cis-entitlement.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Entitlement
          metadata:
            name: cis-entitlement
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 120s
    try:
    - apply:
        file: crs/03_kyma-entitlement.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Entitlement
          metadata:
            name: kyma-entitlement
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 120s
    try:
    - apply:
        file: crs/04_service-manager.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1beta1
          kind: ServiceManager
          metadata:
            name: upgrade-test-subaccount-service-manager
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 480s
    try:
    - apply:
        file: crs/05_cis-local.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: CloudManagement
          metadata:
            name: my-cis
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/06_cloudfoundry-env.yaml
    - assert:
        resource:
          apiVersion: environment.btp.sap.crossplane.io/v1alpha1
          kind: CloudFoundryEnvironment
          metadata:
            name: cf-env-dummy-test-upgrade
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/07_subscription.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Subscription
          metadata:
            name: my-subscription
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 1800s
    try:
    - apply:
        file: crs/08_kyma-env.yaml
    - assert:
        resource:
          apiVersion: environment.btp.sap.crossplane.io/v1alpha1
          kind: KymaEnvironment
          metadata:
            name: my-kyma-env
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/09_directory.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: Directory
          metadata:
            name: my-directory
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/10_directoryentitlement.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: DirectoryEntitlement
          metadata:
            name: directory-ent-cis-local
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/11_serviceinstance.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: ServiceInstance
          metadata:
            name: upgrade-destination-instance
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/12_servicebinding.yaml
    - assert:
        resource:
          apiVersion: account.btp.sap.crossplane.io/v1alpha1
          kind: ServiceBinding
          metadata:
            name: upgrade-destination-binding
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/13_subacountapicredential.yaml
    - assert:
        resource:
          apiVersion: security.btp.sap.crossplane.io/v1alpha1
          kind: SubaccountApiCredential
          metadata:
            name: sac-subaccountapicredentials
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
  - timeouts:
      assert: 180s
    try:
    - apply:
        file: crs/14_globalaccount-trust-configuration.yaml
    - assert:
        resource:
          apiVersion: security.btp.sap.crossplane.io/v1alpha1
          kind: GlobalaccountTrustConfiguration
          metadata:
            name: upgrade-test-globalaccounttrustconfig
          status:
            (conditions[?type == 'Ready']):
            - status: 'True'
            (conditions[?type == 'Synced']):
            - status: 'True'
